name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    name: Validate with HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.1

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: integration
